services:
  mautic:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mysql
      - redis
    environment:
      - MAUTIC_DB_HOST=mysql
      - MAUTIC_DB_PORT=3306
      - MAUTIC_DB_NAME=mautic
      - MAUTIC_DB_USER=mautic
      - MAUTIC_DB_PASSWORD=mautic_password
      - MAUTIC_REDIS_HOST=redis
      - MAUTIC_REDIS_PORT=6379
    volumes:
      - ./var:/var/www/html/var
      - ./plugins:/var/www/html/plugins
    networks:
      - mautic-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=mautic
      - MYSQL_USER=mautic
      - MYSQL_PASSWORD=mautic_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mautic-network

  redis:
    image: redis:7-alpine
    networks:
      - mautic-network

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    networks:
      - mautic-network

volumes:
  mysql_data:

networks:
  mautic-network:
    driver: bridge 